server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ConfigurationCenterInCloud/CentralConfig.git
          searchPaths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:1111/eureka/"